
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/frontend

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root